wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714857719.962561
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.10.11
      5: 0.16.3
      6: 4.28.1
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
